### ISSUE TITLE
Remove nightly features

### ISSUE THREAD

**Issue by JulianWgs** [lukaslueg/restruct#4]
Hello,

very cool project!

Does this project need the nightly features? I would be humbled if you could find a way to disable the use of nightly features. Otherwise it is not possible to use the project on the stable channel.

I can also help :)

Best greetings
Julian

**Comment by lukaslueg** [comment]
Yes, this needs the nightly features and probably will do so for the foreseeable future, as const-related features will only slowly make it into the stable channel.
