### ISSUE TITLE
'Expected `()`, found `u8`'

### ISSUE THREAD

**Issue by shymega** [lukaslueg/restruct#6]
Hi,

I'll publish a minimal example later tomorrow - its late here, but I'm trying to pack a single `u8` variable, which probably is unusual - I'm just implementing the protocol I've been given.

Rust seems to think the `::pack(T)` function is expecting an empty value (or a tuple..?). But when I do `::pack((val))`, that makes no difference.

Apologies if this is a silly question though - any ideas?

Thanks.

**Comment by lukaslueg** [comment]
`::pack` always expects a tuple. The syntax for single values then becomes `::pack((val, ))` (notice the extra comma).

To show it more clearly:

```rust
// Long form
let x: (u8, ) = (42, );
Foo::pack(x);
// Same as
Foo::pack((42, ));
```

**Comment by shymega** [comment]
Hey, I tried what you suggested, thanks for your quick reply and explanation.

I've made a [gist](https://gist.github.com/shymega/e429e7c300ca59a33fc45846834e0339) showing my code so far. It can resolve the `::pack` function just fine, its just a matter of the tuple. No need to worry too much about the various structs, its for a program I'm working on to interface with firmware. 

The suggestion you made results in this error:
```
error[E0308]: mismatched types
  --> src/packer.rs:30:20
   |
30 |         Self::pack((val,))
   |                    ^^^^^^ expected `()`, found tuple
   |
   = note: expected unit type `()`
                  found tuple `(u8,)`
```

Its rather strange. I'm using the latest nightly, as stable isn't supported by one of the crates I use.

Thanks.

**Comment by lukaslueg** [comment]
Ah I see. The problem is the `#[fmt(">B")]`, which should be `#[fmt = ">B"]`. In the current form, the proc-macro doesn't get any parameters, so it derives an empty encoder (expecting the empty tuple).

I'll reopen and get around to improve diagnostics.

**Comment by shymega** [comment]
Gotcha. Just trying that - it works now. Thanks.

I just realised my gist was a secret gist (I uploaded it with `gh`), so I've made it public for reference purposes.

Thanks for looking into it.

**Comment by lukaslueg** [comment]
See 07c07b8ae6f2e3b459fc0edabd362f1e98595a25
