### ISSUE TITLE
Update the crate @ crates.io

### ISSUE THREAD

**Issue by bernii** [lukaslueg/restruct#7]
Hey!

I noticed that the crate published at `crates.io` is a bit outdated - it's using deprecated rustdoc macros which have been already removed in the repo. Would you mind publishing a new crate so that users of the lib can use the crate as a dependency (rather than github repo)? Thanks :)

**Comment by lukaslueg** [comment]
Pushed as 0.1.2

**Comment by bernii** [comment]
thank you! :)
